; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:attiny85]
; platform = atmelavr
; board = attiny85
; framework = arduino

; [env:digispark-tiny]
; platform = atmelavr
; board = digispark-tiny
; framework = arduino

[env:attiny13a]
platform = atmelavr
board = attiny13a
framework = arduino

; MicroCore default internal clock speed
board_build.f_cpu = 9600000L

; Tell PlatformIO to use an Arduino as the ISP programmer
upload_protocol = stk500v1

; IMPORTANT: Replace COM3 with the actual port of your Arduino board
upload_port = /dev/cu.usbmodem1301  

upload_flags =
    -P$UPLOAD_PORT
    -b19200